feat(nvims): add pwnvim to collection

diff --git a/.local/bin/nvims b/.local/bin/nvims
--- a/.local/bin/nvims
+++ b/.local/bin/nvims
@@ -6,10 +6,10 @@
 #
 # alias      | url,url#relative_path    | default or branch name
 readonly neovim_apps=(
-	"astro     | https://github.com/AstroNvim/AstroNvim     | default"
-	"nvchad    | https://github.com/NvChad/NvChad,git@github.com:isvicy/NvChadCustom.git#lua/custom          | default"
-	"starter   | https://github.com/LazyVim/starter         | default"
-	"default   | git@git.enceinte.cc:isvic/lazy.git        | coq"
+  "nvchad    | https://github.com/NvChad/NvChad,git@github.com:isvicy/NvChadCustom.git#lua/custom          | default"
+  "starter   | https://github.com/LazyVim/starter         | default"
+  "pwnvim    | https://github.com/pwnwriter/pwnvim.git    | main"
+  "default   | git@git.knocknoc.xyz:isvicy/nvim.git        | main"
 )
 
 # File name that is overwritten with nvim appname aliases.
@@ -28,208 +28,208 @@ dir=$(pwd)
 # shellcheck disable=SC2120
 gitcheck() {
 
-	# Git variables used to determine if a pull is needed.
-	git fetch
-	upstream=${1:-'@{u}'}
-	local=$(git rev-parse @)
-	remote=$(git rev-parse "$upstream")
-	base=$(git merge-base @ "$upstream")
+  # Git variables used to determine if a pull is needed.
+  git fetch
+  upstream=${1:-'@{u}'}
+  local=$(git rev-parse @)
+  remote=$(git rev-parse "$upstream")
+  base=$(git merge-base @ "$upstream")
 
-	if [[ "$local" == "$remote" ]]; then
-		echo "Up-to-date"
-	elif [[ "$remote" == "$base" ]]; then
-		echo "Need-to-Push"
-	elif [[ "$local" == "$base" ]]; then
-		echo "Need-to-Pull"
-	else
-		echo "Diverged"
-	fi
+  if [[ "$local" == "$remote" ]]; then
+    echo "Up-to-date"
+  elif [[ "$remote" == "$base" ]]; then
+    echo "Need-to-Push"
+  elif [[ "$local" == "$base" ]]; then
+    echo "Need-to-Pull"
+  else
+    echo "Diverged"
+  fi
 }
 
 # --------------------------------------------------------------------------
 #  Remove all spaces from parameter 1.
 
 removeSpaces() {
-	var="$(echo -e "$1" | tr -d '[:space:]')"
-	echo "$var"
+  var="$(echo -e "$1" | tr -d '[:space:]')"
+  echo "$var"
 }
 
 # --------------------------------------------------------------------------
 #  Extract fields from neovim_app array.
 
 buildNeovimAppArray() {
-	for fields in "${neovim_apps[@]}"; do
-		IFS=$'|' read -r alias _url _branch <<<"$fields"
-		alias="$(removeSpaces "$alias")"
-		nvapps+=("$alias")
-	done
+  for fields in "${neovim_apps[@]}"; do
+    IFS=$'|' read -r alias _url _branch <<<"$fields"
+    alias="$(removeSpaces "$alias")"
+    nvapps+=("$alias")
+  done
 }
 
 # --------------------------------------------------------------------------
 #  Clone or Pull selected nvapp
 
 cloneOrPullNvApp() {
-	for fields in "${neovim_apps[@]}"; do
-		IFS=$'|' read -r alias urls branch <<<"$fields"
+  for fields in "${neovim_apps[@]}"; do
+    IFS=$'|' read -r alias urls branch <<<"$fields"
 
-		alias="$(removeSpaces "$alias")"
-		if [[ ${alias} == "default" ]]; then
-			alias=""
-		fi
-		if [[ "$1" == "${alias}" ]]; then
-			if [[ ${alias} == "" ]]; then
-				alias="nvim"
-			fi
-			urls="$(removeSpaces "$urls")"
-			branch="$(removeSpaces "$branch")"
-			IFS=',' read -ra addrs <<<"$urls"
-			for addrInfo in "${addrs[@]}"; do
-				IFS='#' read -r url path <<<"$addrInfo"
-				location=$HOME/.config/$alias/$path
-				if [[ -d "$location" ]]; then
-					pullRepository "$alias" $location
-				else
-					cloneRepository "$alias" "$url" "$branch" "$location"
-				fi
+    alias="$(removeSpaces "$alias")"
+    if [[ ${alias} == "default" ]]; then
+      alias=""
+    fi
+    if [[ "$1" == "${alias}" ]]; then
+      if [[ ${alias} == "" ]]; then
+        alias="nvim"
+      fi
+      urls="$(removeSpaces "$urls")"
+      branch="$(removeSpaces "$branch")"
+      IFS=',' read -ra addrs <<<"$urls"
+      for addrInfo in "${addrs[@]}"; do
+        IFS='#' read -r url path <<<"$addrInfo"
+        location=$HOME/.config/$alias/$path
+        if [[ -d "$location" ]]; then
+          pullRepository "$alias" $location
+        else
+          cloneRepository "$alias" "$url" "$branch" "$location"
+        fi
 
-			done
-		fi
-	done
+      done
+    fi
+  done
 }
 
 # --------------------------------------------------------------------------
 #  Pull repository
 
 pullRepository() {
-	alias="$1"
-	location="$2"
-	runCommandFromDirectory "$location" "git pull"
+  alias="$1"
+  location="$2"
+  runCommandFromDirectory "$location" "git pull"
 }
 
 # --------------------------------------------------------------------------
 #  Clone Repository
 
 cloneRepository() {
-	alias="$1"
-	url="$2"
-	branch="$3"
-	location="$4"
+  alias="$1"
+  url="$2"
+  branch="$3"
+  location="$4"
 
-	git clone "$url" "$location"
-	if [[ $branch != "default" ]]; then
-		runCommandFromDirectory "$location" "git checkout $branch"
-	fi
+  git clone "$url" "$location"
+  if [[ $branch != "default" ]]; then
+    runCommandFromDirectory "$location" "git checkout $branch"
+  fi
 }
 
 # --------------------------------------------------------------------------
 #  Recursively remove directory if present.
 
 removeDirIfPresent() {
-	if [[ -d "$1" ]]; then
-		echo "Removed $1"
-		rm -rf "$1"
-	fi
+  if [[ -d "$1" ]]; then
+    echo "Removed $1"
+    rm -rf "$1"
+  fi
 }
 
 # --------------------------------------------------------------------------
 #  Delete NvimApp from $HOME/.config directory
 
 deleteNvimApp() {
-	for fields in "${neovim_apps[@]}"; do
-		IFS=$'|' read -r alias urls branch <<<"$fields"
+  for fields in "${neovim_apps[@]}"; do
+    IFS=$'|' read -r alias urls branch <<<"$fields"
 
-		alias="$(removeSpaces "$alias")"
-		if [[ ${alias} == "default" ]]; then
-			alias=""
-		fi
-		if [[ "$1" == "${alias}" ]]; then
-			if [[ ${alias} == "" ]]; then
-				alias="nvim"
-			fi
-			echo "Deleting $alias if required."
-			urls="$(removeSpaces "$urls")"
-			branch="$(removeSpaces "$branch")"
-			IFS=',' read -ra addrs <<<"$urls"
-			for addrInfo in "${addrs[@]}"; do
-				IFS='#' read -r url path <<<"$addrInfo"
-				location=$HOME/.config/$alias/$path
-				removeDirIfPresent "$location"
-			done
-			removeDirIfPresent "$HOME"/.cache/"$alias"
-			removeDirIfPresent "$HOME"/.local/share/"$alias"
-			removeDirIfPresent "$HOME"/.local/state/"$alias"
-		fi
-	done
+    alias="$(removeSpaces "$alias")"
+    if [[ ${alias} == "default" ]]; then
+      alias=""
+    fi
+    if [[ "$1" == "${alias}" ]]; then
+      if [[ ${alias} == "" ]]; then
+        alias="nvim"
+      fi
+      echo "Deleting $alias if required."
+      urls="$(removeSpaces "$urls")"
+      branch="$(removeSpaces "$branch")"
+      IFS=',' read -ra addrs <<<"$urls"
+      for addrInfo in "${addrs[@]}"; do
+        IFS='#' read -r url path <<<"$addrInfo"
+        location=$HOME/.config/$alias/$path
+        removeDirIfPresent "$location"
+      done
+      removeDirIfPresent "$HOME"/.cache/"$alias"
+      removeDirIfPresent "$HOME"/.local/share/"$alias"
+      removeDirIfPresent "$HOME"/.local/state/"$alias"
+    fi
+  done
 }
 
 # --------------------------------------------------------------------------
 #  Run a command from another directory.
 
 runCommandFromDirectory() {
-	location="$1"
-	command="$2"
+  location="$1"
+  command="$2"
 
-	cd "$location" || return
+  cd "$location" || return
 
-	if [[ "$(runCommandCheck "$command")" == true ]]; then
-		echo "$command"
-		$command
-	fi
+  if [[ "$(runCommandCheck "$command")" == true ]]; then
+    echo "$command"
+    $command
+  fi
 
-	toWorkingDirectory
+  toWorkingDirectory
 }
 
 # --------------------------------------------------------------------------
 #  Avoid unnecessary pull commands.
 
 runCommandCheck() {
-	command="$1"
-	run_command=true
+  command="$1"
+  run_command=true
 
-	if [[ "$command" == "git pull" ]]; then
-		if [[ "$(gitcheck)" != "Need-to-Pull" ]]; then
-			run_command=false
-		fi
-	fi
+  if [[ "$command" == "git pull" ]]; then
+    if [[ "$(gitcheck)" != "Need-to-Pull" ]]; then
+      run_command=false
+    fi
+  fi
 
-	echo "$run_command"
+  echo "$run_command"
 }
 
 # --------------------------------------------------------------------------
 #  Move to working directory.
 
 toWorkingDirectory() {
-	cd "$dir" || (echo "Returning to working directory failed." && exit)
+  cd "$dir" || (echo "Returning to working directory failed." && exit)
 }
 
 # --------------------------------------------------------------------------
 #  Write neovim aliases to a file that can be sourced.
 
 writeAliasesFile() {
-	echo "# NVIM_APPNAME aliases" >>"$nvimAppNameFile"
-	for nvapp in "${nvapps[@]}"; do
-		if [[ "default" != "$nvapp" ]]; then
-			echo alias nvim-"${nvapp}"=\"NVIM_APPNAME="$nvapp" nvim\" >>"$nvimAppNameFile"
-		fi
-	done
+  echo "# NVIM_APPNAME aliases" >>"$nvimAppNameFile"
+  for nvapp in "${nvapps[@]}"; do
+    if [[ "default" != "$nvapp" ]]; then
+      echo alias nvim-"${nvapp}"=\"NVIM_APPNAME="$nvapp" nvim\" >>"$nvimAppNameFile"
+    fi
+  done
 }
 
 # --------------------------------------------------------------------------
 #  Select Neovim app to switch to.
 
 selectNeovimApp() {
-	config=$(
-		printf "%s\n" "${nvapps[@]}" |
-			fzf --prompt=" Neovim Config  " \
-				--height=35% --layout=reverse --border --exit-0
-	)
+  config=$(
+    printf "%s\n" "${nvapps[@]}" |
+      fzf --prompt=" Neovim Config  " \
+        --height=35% --layout=reverse --border --exit-0
+  )
 
-	if [[ -z $config ]]; then
-		echo "Nothing selected"
-	elif [[ $config == "default" ]]; then
-		config=""
-	fi
-	echo "$config"
+  if [[ -z $config ]]; then
+    echo "Nothing selected"
+  elif [[ $config == "default" ]]; then
+    config=""
+  fi
+  echo "$config"
 }
 
 # --------------------------------------------------------------------------
@@ -240,39 +240,39 @@ selectNeovimApp() {
 
 deleteNvimAppFlag=false
 while getopts 'dh' option; do
-	case "$option" in
-	d)
-		deleteNvimAppFlag=true
-		;;
-	h)
-		echo "Usage: nvims [] [-d] [-h]"
-		exit 1
-		;;
-	*)
-		printf "Usage: nvims [] [-d] [-h]\n"
-		exit 1
-		;;
-	esac
+  case "$option" in
+  d)
+    deleteNvimAppFlag=true
+    ;;
+  h)
+    echo "Usage: nvims [] [-d] [-h]"
+    exit 1
+    ;;
+  *)
+    printf "Usage: nvims [] [-d] [-h]\n"
+    exit 1
+    ;;
+  esac
 done
 
 # -- -----------------------------------------------------------------------
 #  Main logic
 
 main() {
-	buildNeovimAppArray
-	writeAliasesFile
-	choice="$(selectNeovimApp)"
+  buildNeovimAppArray
+  writeAliasesFile
+  choice="$(selectNeovimApp)"
 
-	if [[ "$choice" == "Nothing selected" ]]; then
-		echo "Invalid choice. Exiting" && exit
-	fi
+  if [[ "$choice" == "Nothing selected" ]]; then
+    echo "Invalid choice. Exiting" && exit
+  fi
 
-	if [[ $deleteNvimAppFlag == true ]]; then
-		deleteNvimApp "$choice"
-	else
-		cloneOrPullNvApp "$choice"
-		NVIM_APPNAME="$choice" nvim "$@"
-	fi
+  if [[ $deleteNvimAppFlag == true ]]; then
+    deleteNvimApp "$choice"
+  else
+    cloneOrPullNvApp "$choice"
+    NVIM_APPNAME="$choice" nvim "$@"
+  fi
 }
 
 # --------------------------------------------------------------------------
